/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/full-forecast` | `/full-forecast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/period-forecast` | `/period-forecast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/radar` | `/radar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/satellite` | `/satellite`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/full-forecast` | `/full-forecast`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/period-forecast` | `/period-forecast`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/radar` | `/radar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/satellite` | `/satellite`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/full-forecast${`?${string}` | `#${string}` | ''}` | `/full-forecast${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/period-forecast${`?${string}` | `#${string}` | ''}` | `/period-forecast${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/radar${`?${string}` | `#${string}` | ''}` | `/radar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/satellite${`?${string}` | `#${string}` | ''}` | `/satellite${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/full-forecast` | `/full-forecast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/period-forecast` | `/period-forecast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/radar` | `/radar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/satellite` | `/satellite`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
